import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import type { Approval, Session } from "@mayi/contracts";
import { MayIClient } from "@mayi/sdk";
import "./styles.css";

const api = new MayIClient(location.origin);

function Auth({ onDone }: { onDone: (session: Session) => void }) {
  const [signup, setSignup] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); const data = new FormData(event.currentTarget);
    try { onDone(signup ? await api.signup({ email: String(data.get("email")), password: String(data.get("password")), displayName: String(data.get("name")) }) : await api.signin({ email: String(data.get("email")), password: String(data.get("password")) })); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Authentication failed"); }
  }
  return <main className="auth"><section className="card"><div className="mark">?</div><h1>May I?</h1><p>Review exact actions before agents act.</p><form onSubmit={submit}>{signup && <label>Name<input name="name" autoComplete="name" required /></label>}<label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" minLength={signup ? 12 : 1} autoComplete={signup ? "new-password" : "current-password"} required /></label>{error && <p className="error">{error}</p>}<button>{signup ? "Create workspace" : "Sign in"}</button></form><button className="text" onClick={() => setSignup(!signup)}>{signup ? "Already have an account?" : "Create an account"}</button></section></main>;
}

function ApprovalView({ item, email, back, refresh }: { item: Approval; email: string; back: () => void; refresh: () => Promise<void> }) {
  const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false); const pending = item.state === "PENDING";
  async function decide(decision: "APPROVED" | "DENIED") { setBusy(true); try { await api.decide(item.id, { decision, ...(comment ? { comment } : {}) }); await refresh(); } catch (error) { if (error instanceof Error && error.message.includes("Recent authentication")) { const password = window.prompt("Re-enter your password to decide this high-risk action"); if (password) { await api.stepUp({ email, password }); await api.decide(item.id, { decision, ...(comment ? { comment } : {}) }); await refresh(); } } else window.alert(error instanceof Error ? error.message : "Decision failed"); } finally { setBusy(false); } }
  return <section><button className="text" onClick={back}>← Inbox</button><div className="card detail"><header><span className={`state ${item.state.toLowerCase()}`}>{item.state}</span><small>Expires {new Date(item.expiresAt).toLocaleString()}</small></header><h2>{item.action.kind}</h2><p>{item.explanation}</p><h3>Exact action</h3><pre>{JSON.stringify(item.action, null, 2)}</pre><h3>Evidence ({item.artefacts.length})</h3>{item.artefacts.length ? item.artefacts.map((file) => <a className="file" key={file.id} target="_blank" href={`/api/approvals/${item.id}/artefacts/${file.id}`}>{file.filename}<small>{file.mediaType} · {(file.size / 1024).toFixed(1)} KiB · {file.sha256.slice(0, 12)}…</small></a>) : <p className="muted">No evidence attached.</p>}{pending && <div className="decision"><label>Comment<textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength={4000} /></label><div><button className="deny" disabled={busy} onClick={() => decide("DENIED")}>Deny</button><button disabled={busy} onClick={() => decide("APPROVED")}>Approve</button></div></div>}{item.receipt && <><h3>Signed receipt</h3><textarea className="receipt" readOnly value={item.receipt} /></>}</div></section>;
}

function App() {
  const [session, setSession] = useState<Session | null>(); const [items, setItems] = useState<Approval[]>([]); const [selected, setSelected] = useState<string>(); const [tab, setTab] = useState("inbox"); const [activity, setActivity] = useState<Array<Record<string, unknown>>>([]); const [agents, setAgents] = useState<Array<Record<string, unknown>>>([]); const [secret, setSecret] = useState("");
  async function load() { const values = await api.approvals(); setItems(values); const linked = new URLSearchParams(location.search).get("approval"); if (linked && values.some((x) => x.id === linked)) setSelected(linked); else if (selected && !values.some((x) => x.id === selected)) setSelected(undefined); }
  useEffect(() => { api.session().then(setSession).catch(() => setSession(null)); }, []);
  useEffect(() => { if (session) void load(); }, [session]);
  if (session === undefined) return <div className="loading">Loading…</div>; if (!session) return <Auth onDone={(value) => { setSession(value); const returnTo = new URLSearchParams(location.search).get("returnTo"); if (returnTo?.startsWith("/api/oauth/authorize?")) location.assign(returnTo); }} />;
  const current = items.find((item) => item.id === selected); if (current) return <div className="shell"><ApprovalView item={current} email={session.user.email} back={() => setSelected(undefined)} refresh={load} /></div>;
  async function openTab(next: string) { setTab(next); if (next === "activity") setActivity(await api.activity()); if (next === "agents") setAgents(await api.agents()); }
  async function createAgent(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await api.createAgent({ name: String(data.get("name")), scopes: ["approval:create", "approval:read", "approval:cancel"] }); setSecret(result.token); setAgents(await api.agents()); event.currentTarget.reset(); }
  return <><header className="top"><strong>May I?</strong><nav>{["inbox", "history", "agents", "activity"].map((name) => <button className={tab === name ? "active" : "text"} onClick={() => openTab(name)} key={name}>{name}</button>)}</nav><button className="text" onClick={async () => { await api.signout(); setSession(null); }}>Sign out</button></header><main className="shell"><p className="eyebrow">{session.workspace.name}</p>{tab === "inbox" || tab === "history" ? <><h1>{tab === "inbox" ? "Pending approvals" : "History"}</h1><div className="list">{items.filter((item) => tab === "inbox" ? item.state === "PENDING" : item.state !== "PENDING" && item.state !== "DRAFT").map((item) => <button className="request" key={item.id} onClick={() => setSelected(item.id)}><span><strong>{item.action.kind}</strong><small>{item.explanation}</small></span><span className={`state ${item.state.toLowerCase()}`}>{item.state}</span></button>)}</div></> : tab === "agents" ? <><h1>Connected agents</h1><form className="inline card" onSubmit={createAgent}><input name="name" placeholder="Agent name" required /><button>New headless agent</button></form>{secret && <div className="notice"><strong>Copy this token now.</strong><code>{secret}</code></div>}<div className="list">{agents.map((agent) => <div className="request" key={String(agent.id)}><span><strong>{String(agent.name)}</strong><small>{(agent.scopes as string[]).join(", ")}</small></span></div>)}</div></> : <><h1>Security activity</h1><div className="list">{activity.map((entry) => <div className="request" key={String(entry.id)}><span><strong>{String(entry.eventType)}</strong><small>{new Date(String(entry.createdAt)).toLocaleString()}</small></span></div>)}</div></>}</main></>;
}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
