import { useCallback, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect, useLocalSearchParams, router } from "expo-router";
import * as LocalAuthentication from "expo-local-authentication";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import type { Approval } from "@mayi/contracts";
import { approval, credentials, decide } from "../../lib/api";

export default function Detail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [item, setItem] = useState<Approval>(); const [comment, setComment] = useState("");
  const load = useCallback(() => { if (id) void approval(id).then(setItem).catch((error) => Alert.alert("Could not load", error.message)); }, [id]); useFocusEffect(load);
  async function act(value: "APPROVED" | "DENIED") { const supported = await LocalAuthentication.hasHardwareAsync(); if (supported) { const result = await LocalAuthentication.authenticateAsync({ promptMessage: value === "APPROVED" ? "Approve this exact action" : "Deny this request" }); if (!result.success) return; } try { setItem(await decide(id, value, comment)); } catch (error) { const message = error instanceof Error ? error.message : "Refresh and try again"; Alert.alert("Decision rejected", message, message.includes("Recent authentication") ? [{ text: "Cancel" }, { text: "Sign in again", onPress: () => router.push("/login") }] : undefined); load(); } }
  if (!item) return null;
  return <ScrollView contentContainerStyle={styles.page}><View style={styles.row}><Text style={styles.state}>{item.state}</Text><Text>{new Date(item.expiresAt).toLocaleString()}</Text></View><Text style={styles.title}>{item.action.kind}</Text><Text style={styles.explanation}>{item.explanation}</Text><Text style={styles.heading}>Exact action</Text><Text selectable style={styles.code}>{JSON.stringify(item.action, null, 2)}</Text><Text style={styles.heading}>Evidence ({item.artefacts.length})</Text>{item.artefacts.map((file) => <Pressable key={file.id} style={styles.file} onPress={async () => { const { origin, token } = await credentials(); if (!origin || !token || !FileSystem.cacheDirectory) return; const destination = `${FileSystem.cacheDirectory}${file.id}-${file.filename.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const saved = await FileSystem.downloadAsync(`${origin}/api/approvals/${item.id}/artefacts/${file.id}`, destination, { headers: { Authorization: `Bearer ${token}` } }); await Sharing.shareAsync(saved.uri, { mimeType: file.mediaType }); }}><Text style={styles.fileName}>{file.filename}</Text><Text style={styles.small}>{file.mediaType} · {(file.size / 1024).toFixed(1)} KiB</Text></Pressable>)}{item.state === "PENDING" && <><TextInput style={styles.comment} value={comment} onChangeText={setComment} placeholder="Optional comment" multiline /><View style={styles.actions}><Pressable style={[styles.button, styles.deny]} onPress={() => act("DENIED")}><Text style={styles.buttonText}>Deny</Text></Pressable><Pressable style={styles.button} onPress={() => act("APPROVED")}><Text style={styles.buttonText}>Approve</Text></Pressable></View></>}<Pressable onPress={() => router.back()}><Text style={styles.back}>Back to inbox</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ page: { padding: 20, gap: 12 }, row: { flexDirection: "row", justifyContent: "space-between" }, state: { color: "#755800", fontWeight: "700" }, title: { fontSize: 27, fontWeight: "700", color: "#18241f" }, explanation: { fontSize: 17, lineHeight: 25 }, heading: { fontSize: 16, fontWeight: "700", marginTop: 12 }, code: { fontFamily: "monospace", backgroundColor: "#e9eeeb", padding: 14, borderRadius: 10 }, file: { padding: 14, backgroundColor: "white", borderWidth: 1, borderColor: "#dce3df", borderRadius: 10 }, fileName: { color: "#176b51", fontWeight: "600" }, small: { color: "#61776d", marginTop: 4 }, comment: { minHeight: 80, backgroundColor: "white", borderWidth: 1, borderColor: "#bdcac4", borderRadius: 10, padding: 12, textAlignVertical: "top" }, actions: { flexDirection: "row", gap: 10 }, button: { flex: 1, backgroundColor: "#176b51", padding: 15, borderRadius: 10, alignItems: "center" }, deny: { backgroundColor: "#a6333c" }, buttonText: { color: "white", fontWeight: "700" }, back: { color: "#176b51", textAlign: "center", padding: 15 } });
